base_lr: 0.1
batch_size: 8
config: config/my_subject_train.yaml
device:
- 0
- 1
eval_interval: 5
feeder: feeders.feeder.Feeder
ignore_weights: []
log_interval: 100
model: model.agcn.Model
model_args:
  graph: graph.my_graph.Graph
  graph_args:
    labeling_mode: spatial
  num_class: 4
  num_person: 2
  num_point: 21
model_saved_name: ./runs/my_cs_agcn
nesterov: true
num_epoch: 50
num_worker: 32
only_train_epoch: 0
only_train_part: false
optimizer: SGD
phase: train
print_log: true
save_interval: 2
save_score: false
seed: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 30
- 40
test_batch_size: 8
test_feeder_args:
  data_path: ./data/mydata/gen/xsub/val_data_joint.npy
  label_path: ./data/mydata/gen/xsub/val_label.pkl
train_feeder_args:
  data_path: ./data/mydata/gen/xsub/train_data_joint.npy
  debug: false
  label_path: ./data/mydata/gen/xsub/train_label.pkl
  normalization: false
  random_choose: false
  random_move: false
  random_shift: false
  window_size: -1
warm_up_epoch: 0
weight_decay: 0.0001
weights: null
work_dir: ./work_dir/my_agcn
